using ClosedXML.Excel;
using EAMAS.Core.Enums;
using EAMAS.Core.Models;
using EAMAS.Core.Services;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;

namespace EAMAS.Desktop.Services
{
    /// <summary>All data collected for one report run — passed to both PDF and Excel exporters.</summary>
    public class ReportBundle
    {
        public string OrganizationName  { get; set; } = string.Empty;
        public string EmployeeName      { get; set; } = string.Empty;
        public string EmployeeRole      { get; set; } = string.Empty;
        public string EmployeeDepartment{ get; set; } = string.Empty;
        public string GeneratedBy       { get; set; } = string.Empty;
        public DateTime From            { get; set; }
        public DateTime To              { get; set; }   // exclusive upper bound
        public DateTime GeneratedAt     { get; set; } = DateTime.Now;

        // Core daily data
        public List<DailySummary>    DailySummaries  { get; set; } = new();
        // Per-app detail
        public List<AppUsageDetail>  AppDetails      { get; set; } = new();
        // Category totals
        public Dictionary<ActivityCategory, TimeSpan> CategoryTotals { get; set; } = new();
        // Hour 0-23 activity
        public List<HourlyActivity>  HourlyBreakdown { get; set; } = new();
        // Alerts fired in period
        public List<Alert>           Alerts          { get; set; } = new();
        // Audit log (admin only; empty otherwise)
        public List<AuditLog>        AuditLogs       { get; set; } = new();

        // Derived totals (computed once in ViewModel)
        public TimeSpan TotalActive      { get; set; }
        public TimeSpan TotalIdle        { get; set; }
        public TimeSpan TotalProductive  { get; set; }
        public TimeSpan TotalDistracting { get; set; }
        public int      AvgScore         { get; set; }
        public int      TotalScreenshots { get; set; }

        public string PeriodLabel =>
            $"{From:MMM d, yyyy}  –  {To.AddDays(-1):MMM d, yyyy}";
    }

    public static class ExportService
    {
        static ExportService()
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }

        // ── Excel ────────────────────────────────────────────────────────────────

        public static void ExportToExcel(ReportBundle r, string path)
        {
            using var wb = new XLWorkbook();

            AddSummarySheet(wb, r);
            AddDailySheet(wb, r);
            AddAppUsageSheet(wb, r);
            AddCategorySheet(wb, r);
            AddHourlySheet(wb, r);
            if (r.Alerts.Any())   AddAlertsSheet(wb, r);
            if (r.AuditLogs.Any()) AddAuditSheet(wb, r);

            wb.SaveAs(path);
        }

        private static void AddSummarySheet(XLWorkbook wb, ReportBundle r)
        {
            var ws = wb.Worksheets.Add("Summary");
            ws.ShowGridLines = false;

            // Title block
            ws.Cell(1, 1).Value = "EAMAS — Employee Activity Report";
            ws.Cell(1, 1).Style.Font.Bold = true;
            ws.Cell(1, 1).Style.Font.FontSize = 16;
            ws.Cell(1, 1).Style.Font.FontColor = XLColor.FromHtml("#1E40AF");
            ws.Range(1, 1, 1, 6).Merge();

            ws.Cell(2, 1).Value = r.PeriodLabel;
            ws.Cell(2, 1).Style.Font.FontSize = 11;
            ws.Cell(2, 1).Style.Font.FontColor = XLColor.FromHtml("#64748B");
            ws.Range(2, 1, 2, 6).Merge();

            int row = 4;
            void Info(string label, string value)
            {
                ws.Cell(row, 1).Value = label;
                ws.Cell(row, 1).Style.Font.Bold = true;
                ws.Cell(row, 1).Style.Font.FontColor = XLColor.FromHtml("#64748B");
                ws.Cell(row, 2).Value = value;
                row++;
            }

            Info("Organisation", r.OrganizationName);
            Info("Employee",     r.EmployeeName);
            Info("Role",         r.EmployeeRole);
            Info("Department",   r.EmployeeDepartment);
            Info("Generated",    r.GeneratedAt.ToString("yyyy-MM-dd HH:mm"));
            Info("Generated By", r.GeneratedBy);
            row++;

            // KPI table
            var kpiHeaders = new[] { "METRIC", "VALUE" };
            WriteHeaderRow(ws, row, kpiHeaders, "#1E40AF");
            row++;

            void Kpi(string metric, string value)
            {
                ws.Cell(row, 1).Value = metric;
                ws.Cell(row, 2).Value = value;
                AlternateRow(ws, row, 2);
                row++;
            }

            Kpi("Total Active Time",        FormatTime(r.TotalActive));
            Kpi("Total Idle Time",          FormatTime(r.TotalIdle));
            Kpi("Total Productive Time",    FormatTime(r.TotalProductive));
            Kpi("Total Distracting Time",   FormatTime(r.TotalDistracting));
            Kpi("Average Productivity Score", $"{r.AvgScore}%");
            Kpi("Total Screenshots",        r.TotalScreenshots.ToString());
            Kpi("Active Days",              r.DailySummaries.Count(s => s.ActiveTime.TotalMinutes >= 5).ToString());
            Kpi("Best Day Score",           r.DailySummaries.Any()
                ? $"{r.DailySummaries.Max(s => s.ProductivityScore)}% — {r.DailySummaries.OrderByDescending(s => s.ProductivityScore).First().Date:ddd MMM d}"
                : "—");
            Kpi("Alert Count",              r.Alerts.Count.ToString());

            ws.Column(1).Width = 28;
            ws.Column(2).Width = 40;
        }

        private static void AddDailySheet(XLWorkbook wb, ReportBundle r)
        {
            var ws = wb.Worksheets.Add("Daily Breakdown");
            ws.ShowGridLines = false;

            var headers = new[]
            {
                "DATE", "DAY", "ACTIVE TIME", "IDLE TIME",
                "PRODUCTIVE", "DISTRACTING", "NEUTRAL",
                "SCORE", "SCREENSHOTS", "TOP APP"
            };
            WriteHeaderRow(ws, 1, headers, "#1E40AF");

            int row = 2;
            foreach (var s in r.DailySummaries)
            {
                var neutral = s.ActiveTime - s.ProductiveTime - s.DistractingTime;
                if (neutral < TimeSpan.Zero) neutral = TimeSpan.Zero;
                ws.Cell(row, 1).Value  = s.Date.ToString("yyyy-MM-dd");
                ws.Cell(row, 2).Value  = s.Date.ToString("dddd");
                ws.Cell(row, 3).Value  = FormatTime(s.ActiveTime);
                ws.Cell(row, 4).Value  = FormatTime(s.IdleTime);
                ws.Cell(row, 5).Value  = FormatTime(s.ProductiveTime);
                ws.Cell(row, 6).Value  = FormatTime(s.DistractingTime);
                ws.Cell(row, 7).Value  = FormatTime(neutral);
                ws.Cell(row, 8).Value  = s.ProductivityScore;
                ws.Cell(row, 9).Value  = s.ScreenshotCount;
                ws.Cell(row, 10).Value = s.TopApps.FirstOrDefault().App ?? "—";

                // Score cell color
                var scoreCell = ws.Cell(row, 8);
                scoreCell.Style.Font.Bold = true;
                scoreCell.Style.Font.FontColor = s.ProductivityScore >= 70
                    ? XLColor.FromHtml("#16A34A")
                    : s.ProductivityScore >= 40
                        ? XLColor.FromHtml("#D97706")
                        : XLColor.FromHtml("#DC2626");

                AlternateRow(ws, row, 10);
                row++;
            }

            AutofitColumns(ws, 10);
        }

        private static void AddAppUsageSheet(XLWorkbook wb, ReportBundle r)
        {
            var ws = wb.Worksheets.Add("App Usage");
            ws.ShowGridLines = false;

            var headers = new[]
            {
                "APPLICATION", "PROCESS", "CATEGORY",
                "TOTAL TIME", "% OF ACTIVE", "PRODUCTIVITY RATING"
            };
            WriteHeaderRow(ws, 1, headers, "#1E40AF");

            var totalActiveTicks = r.TotalActive.Ticks < 1 ? 1 : r.TotalActive.Ticks;
            int row = 2;
            foreach (var a in r.AppDetails)
            {
                var pct = (double)a.TotalDuration.Ticks / totalActiveTicks * 100;
                ws.Cell(row, 1).Value = a.ApplicationName;
                ws.Cell(row, 2).Value = a.ProcessName;
                ws.Cell(row, 3).Value = a.Category.ToString();
                ws.Cell(row, 4).Value = FormatTime(a.TotalDuration);
                ws.Cell(row, 5).Value = $"{pct:F1}%";
                ws.Cell(row, 6).Value = $"{a.ProductivityRating}%";

                // Category colour
                ws.Cell(row, 3).Style.Font.FontColor = a.Category switch
                {
                    ActivityCategory.Productive   => XLColor.FromHtml("#16A34A"),
                    ActivityCategory.Distracting  => XLColor.FromHtml("#DC2626"),
                    ActivityCategory.Neutral      => XLColor.FromHtml("#D97706"),
                    _                             => XLColor.FromHtml("#64748B")
                };

                AlternateRow(ws, row, 6);
                row++;
            }

            AutofitColumns(ws, 6);
        }

        private static void AddCategorySheet(XLWorkbook wb, ReportBundle r)
        {
            var ws = wb.Worksheets.Add("Category Analysis");
            ws.ShowGridLines = false;

            ws.Cell(1, 1).Value = "TIME BY CATEGORY";
            ws.Cell(1, 1).Style.Font.Bold = true;
            ws.Cell(1, 1).Style.Font.FontSize = 13;

            var headers = new[] { "CATEGORY", "TOTAL TIME", "PERCENTAGE", "DESCRIPTION" };
            WriteHeaderRow(ws, 2, headers, "#1E40AF");

            var totalTicks = r.CategoryTotals.Values.Sum(t => t.Ticks);
            if (totalTicks == 0) totalTicks = 1;

            int row = 3;
            var catDescriptions = new Dictionary<ActivityCategory, string>
            {
                [ActivityCategory.Productive]  = "Work-related applications contributing positively",
                [ActivityCategory.Neutral]     = "General or uncategorised applications",
                [ActivityCategory.Distracting] = "Non-work applications reducing productivity",
                [ActivityCategory.Unknown]     = "Newly seen applications not yet categorised"
            };

            foreach (ActivityCategory cat in Enum.GetValues<ActivityCategory>())
            {
                r.CategoryTotals.TryGetValue(cat, out var ts);
                var pct = (double)ts.Ticks / totalTicks * 100;
                ws.Cell(row, 1).Value = cat.ToString();
                ws.Cell(row, 2).Value = FormatTime(ts);
                ws.Cell(row, 3).Value = $"{pct:F1}%";
                ws.Cell(row, 4).Value = catDescriptions.GetValueOrDefault(cat, "");
                AlternateRow(ws, row, 4);
                row++;
            }

            // Also add idle
            ws.Cell(row, 1).Value = "Idle";
            ws.Cell(row, 2).Value = FormatTime(r.TotalIdle);
            ws.Cell(row, 3).Value = "—";
            ws.Cell(row, 4).Value = "No keyboard/mouse input detected";
            AlternateRow(ws, row, 4);

            AutofitColumns(ws, 4);
        }

        private static void AddHourlySheet(XLWorkbook wb, ReportBundle r)
        {
            var ws = wb.Worksheets.Add("Hourly Patterns");
            ws.ShowGridLines = false;

            var headers = new[]
            {
                "HOUR", "TIME SLOT", "ACTIVE TIME",
                "PRODUCTIVE TIME", "DISTRACTING TIME", "PRODUCTIVITY %"
            };
            WriteHeaderRow(ws, 1, headers, "#1E40AF");

            int row = 2;
            foreach (var h in r.HourlyBreakdown)
            {
                var prodPct = h.ActiveTime.Ticks < 1 ? 0
                    : (double)h.ProductiveTime.Ticks / h.ActiveTime.Ticks * 100;

                ws.Cell(row, 1).Value = h.Hour;
                ws.Cell(row, 2).Value = $"{h.Hour:D2}:00 – {(h.Hour + 1) % 24:D2}:00";
                ws.Cell(row, 3).Value = FormatTime(h.ActiveTime);
                ws.Cell(row, 4).Value = FormatTime(h.ProductiveTime);
                ws.Cell(row, 5).Value = FormatTime(h.DistractingTime);
                ws.Cell(row, 6).Value = $"{prodPct:F0}%";

                if (h.ActiveTime.TotalMinutes >= 30)
                    ws.Cell(row, 3).Style.Font.Bold = true;

                AlternateRow(ws, row, 6);
                row++;
            }

            AutofitColumns(ws, 6);
        }

        private static void AddAlertsSheet(XLWorkbook wb, ReportBundle r)
        {
            var ws = wb.Worksheets.Add("Alerts");
            ws.ShowGridLines = false;

            var headers = new[] { "DATE & TIME", "TYPE", "MESSAGE", "RESOLVED" };
            WriteHeaderRow(ws, 1, headers, "#991B1B");

            int row = 2;
            foreach (var a in r.Alerts)
            {
                ws.Cell(row, 1).Value = a.CreatedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
                ws.Cell(row, 2).Value = a.Type.ToString();
                ws.Cell(row, 3).Value = a.Message;
                ws.Cell(row, 4).Value = a.IsResolved ? "Yes" : "No";

                ws.Cell(row, 4).Style.Font.FontColor = a.IsResolved
                    ? XLColor.FromHtml("#16A34A")
                    : XLColor.FromHtml("#DC2626");

                AlternateRow(ws, row, 4);
                row++;
            }

            AutofitColumns(ws, 4);
        }

        private static void AddAuditSheet(XLWorkbook wb, ReportBundle r)
        {
            var ws = wb.Worksheets.Add("Audit Log");
            ws.ShowGridLines = false;

            var headers = new[] { "TIMESTAMP", "USER", "ACTION", "DETAILS" };
            WriteHeaderRow(ws, 1, headers, "#374151");

            int row = 2;
            foreach (var e in r.AuditLogs)
            {
                ws.Cell(row, 1).Value = e.Timestamp.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss");
                ws.Cell(row, 2).Value = e.ActorName;
                ws.Cell(row, 3).Value = e.Action;
                ws.Cell(row, 4).Value = e.Details;
                AlternateRow(ws, row, 4);
                row++;
            }

            AutofitColumns(ws, 4);
        }

        // ── PDF ──────────────────────────────────────────────────────────────────

        public static void ExportToPdf(ReportBundle r, string path)
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.DefaultTextStyle(t => t.FontFamily("Arial").FontSize(9).FontColor("#1E293B"));

                    page.Header().Element(c => PdfHeader(c, r));
                    page.Footer().Element(c => PdfFooter(c, r));
                    page.Content().Element(c => PdfContent(c, r));
                });
            }).GeneratePdf(path);
        }

        private static void PdfHeader(IContainer c, ReportBundle r)
        {
            c.BorderBottom(1).BorderColor("#E2E8F0").PaddingBottom(10).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("EAMAS — Employee Activity Report")
                        .FontSize(16).Bold().FontColor("#1E40AF");
                    col.Item().Text(r.PeriodLabel)
                        .FontSize(9).FontColor("#64748B");
                });
                row.ConstantItem(160).AlignRight().Column(col =>
                {
                    col.Item().Text(r.OrganizationName).Bold().AlignRight();
                    col.Item().Text($"Generated: {r.GeneratedAt:yyyy-MM-dd HH:mm}").FontColor("#64748B").AlignRight();
                });
            });
        }

        private static void PdfFooter(IContainer c, ReportBundle r)
        {
            c.BorderTop(1).BorderColor("#E2E8F0").PaddingTop(6).Row(row =>
            {
                row.RelativeItem().Text($"Confidential — {r.OrganizationName}").FontColor("#94A3B8").FontSize(8);
                row.RelativeItem().AlignCenter().Text(txt =>
                {
                    txt.Span("Page ").FontColor("#94A3B8").FontSize(8);
                    txt.CurrentPageNumber().FontColor("#94A3B8").FontSize(8);
                    txt.Span(" of ").FontColor("#94A3B8").FontSize(8);
                    txt.TotalPages().FontColor("#94A3B8").FontSize(8);
                });
                row.RelativeItem().AlignRight().Text("EAMAS v" + UpdateService.CurrentVersion.ToString(3)).FontColor("#94A3B8").FontSize(8);
            });
        }

        private static void PdfContent(IContainer c, ReportBundle r)
        {
            c.Column(col =>
            {
                col.Spacing(16);

                // ── Employee info block
                col.Item().Element(x => PdfInfoBlock(x, r));

                // ── KPI summary
                col.Item().Element(x => PdfKpiTable(x, r));

                // ── Daily breakdown
                col.Item().Element(x => PdfDailyTable(x, r));

                // ── App usage
                if (r.AppDetails.Any())
                    col.Item().Element(x => PdfAppTable(x, r));

                // ── Category analysis
                if (r.CategoryTotals.Any())
                    col.Item().Element(x => PdfCategoryTable(x, r));

                // ── Hourly patterns
                col.Item().Element(x => PdfHourlyTable(x, r));

                // ── Alerts
                if (r.Alerts.Any())
                    col.Item().Element(x => PdfAlertsTable(x, r));

                // ── Audit log
                if (r.AuditLogs.Any())
                    col.Item().Element(x => PdfAuditTable(x, r));
            });
        }

        private static void PdfInfoBlock(IContainer c, ReportBundle r)
        {
            c.Background("#F8FAFC").Border(1).BorderColor("#E2E8F0").Padding(12).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("Employee").FontSize(8).FontColor("#64748B");
                    col.Item().Text(r.EmployeeName).Bold();
                    col.Item().PaddingTop(4).Text("Role").FontSize(8).FontColor("#64748B");
                    col.Item().Text(r.EmployeeRole);
                });
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("Department").FontSize(8).FontColor("#64748B");
                    col.Item().Text(string.IsNullOrWhiteSpace(r.EmployeeDepartment) ? "—" : r.EmployeeDepartment);
                    col.Item().PaddingTop(4).Text("Organisation").FontSize(8).FontColor("#64748B");
                    col.Item().Text(r.OrganizationName);
                });
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("Report Period").FontSize(8).FontColor("#64748B");
                    col.Item().Text(r.PeriodLabel);
                    col.Item().PaddingTop(4).Text("Generated By").FontSize(8).FontColor("#64748B");
                    col.Item().Text(r.GeneratedBy);
                });
            });
        }

        private static void PdfKpiTable(IContainer c, ReportBundle r)
        {
            c.Column(col =>
            {
                col.Item().Text("Executive Summary").FontSize(12).Bold().FontColor("#1E40AF");
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.RelativeColumn(3);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(3);
                        cd.RelativeColumn(2);
                    });

                    void Kpi(string label, string value, string? color = null)
                    {
                        t.Cell().Background("#F1F5F9").Padding(8).Column(col =>
                        {
                            col.Item().Text(label).FontSize(7).FontColor("#64748B");
                            col.Item().Text(value).FontSize(13).Bold()
                               .FontColor(color ?? "#1E293B");
                        });
                    }

                    var scoreColor = r.AvgScore >= 70 ? "#16A34A" : r.AvgScore >= 40 ? "#D97706" : "#DC2626";

                    Kpi("TOTAL ACTIVE TIME",      FormatTime(r.TotalActive));
                    Kpi("AVG PRODUCTIVITY SCORE", $"{r.AvgScore}%", scoreColor);
                    Kpi("TOTAL PRODUCTIVE TIME",  FormatTime(r.TotalProductive));
                    Kpi("TOTAL DISTRACTING TIME", FormatTime(r.TotalDistracting));
                    Kpi("TOTAL IDLE TIME",        FormatTime(r.TotalIdle));
                    Kpi("TOTAL SCREENSHOTS",      r.TotalScreenshots.ToString());
                    Kpi("ACTIVE DAYS",            r.DailySummaries.Count(s => s.ActiveTime.TotalMinutes >= 5).ToString());
                    Kpi("ALERTS FIRED",           r.Alerts.Count.ToString());
                });
            });
        }

        private static void PdfDailyTable(IContainer c, ReportBundle r)
        {
            c.Column(col =>
            {
                col.Item().Text("Daily Breakdown").FontSize(12).Bold().FontColor("#1E40AF");
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.RelativeColumn(2.2f);
                        cd.RelativeColumn(1.6f);
                        cd.RelativeColumn(1.4f);
                        cd.RelativeColumn(1.6f);
                        cd.RelativeColumn(1.6f);
                        cd.RelativeColumn(1);
                        cd.RelativeColumn(1);
                    });

                    PdfTableHeader(t, new[] { "DATE", "ACTIVE", "IDLE", "PRODUCTIVE", "DISTRACTING", "SCORE", "SHOTS" });

                    bool alt = false;
                    foreach (var s in r.DailySummaries)
                    {
                        var bg = alt ? "#F8FAFC" : "#FFFFFF";
                        alt = !alt;
                        var scoreColor = s.ProductivityScore >= 70 ? "#16A34A"
                            : s.ProductivityScore >= 40 ? "#D97706" : "#DC2626";

                        PdfCell(t, s.Date.ToString("ddd, MMM d"), bg);
                        PdfCell(t, FormatTime(s.ActiveTime), bg);
                        PdfCell(t, FormatTime(s.IdleTime), bg);
                        PdfCell(t, FormatTime(s.ProductiveTime), bg);
                        PdfCell(t, FormatTime(s.DistractingTime), bg);
                        t.Cell().Background(bg).Padding(5).AlignCenter()
                            .Text($"{s.ProductivityScore}%").Bold().FontColor(scoreColor);
                        PdfCell(t, s.ScreenshotCount.ToString(), bg, center: true);
                    }
                });
            });
        }

        private static void PdfAppTable(IContainer c, ReportBundle r)
        {
            c.Column(col =>
            {
                col.Item().Text("Application Usage").FontSize(12).Bold().FontColor("#1E40AF");
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.RelativeColumn(3);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(1.5f);
                        cd.RelativeColumn(1.5f);
                        cd.RelativeColumn(1.5f);
                    });

                    PdfTableHeader(t, new[] { "APPLICATION", "CATEGORY", "TOTAL TIME", "% OF ACTIVE", "PROD. RATING" });

                    var totalTicks = r.TotalActive.Ticks < 1 ? 1 : r.TotalActive.Ticks;
                    bool alt = false;
                    foreach (var a in r.AppDetails)
                    {
                        var bg = alt ? "#F8FAFC" : "#FFFFFF";
                        alt = !alt;
                        var pct = (double)a.TotalDuration.Ticks / totalTicks * 100;
                        var catColor = a.Category switch
                        {
                            ActivityCategory.Productive  => "#16A34A",
                            ActivityCategory.Distracting => "#DC2626",
                            ActivityCategory.Neutral     => "#D97706",
                            _                            => "#64748B"
                        };

                        PdfCell(t, a.ApplicationName, bg, bold: true);
                        t.Cell().Background(bg).Padding(5).Text(a.Category.ToString()).FontColor(catColor);
                        PdfCell(t, FormatTime(a.TotalDuration), bg);
                        PdfCell(t, $"{pct:F1}%", bg, center: true);
                        PdfCell(t, $"{a.ProductivityRating}%", bg, center: true);
                    }
                });
            });
        }

        private static void PdfCategoryTable(IContainer c, ReportBundle r)
        {
            c.Column(col =>
            {
                col.Item().Text("Category Analysis").FontSize(12).Bold().FontColor("#1E40AF");
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(1.5f);
                        cd.RelativeColumn(4);
                    });

                    PdfTableHeader(t, new[] { "CATEGORY", "TOTAL TIME", "PERCENTAGE", "DESCRIPTION" });

                    var totalTicks = r.CategoryTotals.Values.Sum(x => x.Ticks);
                    if (totalTicks == 0) totalTicks = 1;
                    bool alt = false;

                    var descriptions = new Dictionary<ActivityCategory, string>
                    {
                        [ActivityCategory.Productive]  = "Work-related, score-boosting activity",
                        [ActivityCategory.Neutral]      = "General or uncategorised usage",
                        [ActivityCategory.Distracting]  = "Non-work applications reducing score",
                        [ActivityCategory.Unknown]       = "Not yet categorised by the system"
                    };

                    foreach (ActivityCategory cat in Enum.GetValues<ActivityCategory>())
                    {
                        r.CategoryTotals.TryGetValue(cat, out var ts);
                        var bg = alt ? "#F8FAFC" : "#FFFFFF";
                        alt = !alt;
                        PdfCell(t, cat.ToString(), bg);
                        PdfCell(t, FormatTime(ts), bg);
                        PdfCell(t, $"{(double)ts.Ticks / totalTicks * 100:F1}%", bg, center: true);
                        PdfCell(t, descriptions.GetValueOrDefault(cat, ""), bg);
                    }

                    // Idle row
                    var idleBg = alt ? "#F8FAFC" : "#FFFFFF";
                    PdfCell(t, "Idle", idleBg);
                    PdfCell(t, FormatTime(r.TotalIdle), idleBg);
                    PdfCell(t, "—", idleBg, center: true);
                    PdfCell(t, "No keyboard/mouse input detected", idleBg);
                });
            });
        }

        private static void PdfHourlyTable(IContainer c, ReportBundle r)
        {
            var activeHours = r.HourlyBreakdown.Where(h => h.ActiveTime.TotalMinutes >= 1).ToList();
            if (!activeHours.Any()) return;

            c.Column(col =>
            {
                col.Item().Text("Hourly Activity Patterns").FontSize(12).Bold().FontColor("#1E40AF");
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.ConstantColumn(70);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(1.5f);
                    });

                    PdfTableHeader(t, new[] { "HOUR", "TIME SLOT", "ACTIVE", "PRODUCTIVE", "PROD %" });

                    bool alt = false;
                    foreach (var h in activeHours)
                    {
                        var bg = alt ? "#F8FAFC" : "#FFFFFF";
                        alt = !alt;
                        var prodPct = h.ActiveTime.Ticks < 1 ? 0
                            : (double)h.ProductiveTime.Ticks / h.ActiveTime.Ticks * 100;

                        PdfCell(t, $"{h.Hour:D2}:00", bg, center: true);
                        PdfCell(t, $"{h.Hour:D2}:00 – {(h.Hour + 1) % 24:D2}:00", bg);
                        PdfCell(t, FormatTime(h.ActiveTime), bg);
                        PdfCell(t, FormatTime(h.ProductiveTime), bg);
                        PdfCell(t, $"{prodPct:F0}%", bg, center: true);
                    }
                });
            });
        }

        private static void PdfAlertsTable(IContainer c, ReportBundle r)
        {
            c.Column(col =>
            {
                col.Item().Text("Alerts").FontSize(12).Bold().FontColor("#991B1B");
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.ConstantColumn(110);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(5);
                        cd.ConstantColumn(60);
                    });

                    PdfTableHeader(t, new[] { "DATE & TIME", "TYPE", "MESSAGE", "RESOLVED" }, "#991B1B");

                    bool alt = false;
                    foreach (var a in r.Alerts)
                    {
                        var bg = alt ? "#FEF2F2" : "#FFFFFF";
                        alt = !alt;
                        PdfCell(t, a.CreatedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm"), bg);
                        PdfCell(t, a.Type.ToString(), bg);
                        PdfCell(t, a.Message, bg);
                        t.Cell().Background(bg).Padding(5).AlignCenter()
                            .Text(a.IsResolved ? "Yes" : "No")
                            .FontColor(a.IsResolved ? "#16A34A" : "#DC2626").Bold();
                    }
                });
            });
        }

        private static void PdfAuditTable(IContainer c, ReportBundle r)
        {
            c.Column(col =>
            {
                col.Item().Text("Audit Log").FontSize(12).Bold().FontColor("#374151");
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.ConstantColumn(120);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(5);
                    });

                    PdfTableHeader(t, new[] { "TIMESTAMP", "USER", "ACTION", "DETAILS" }, "#374151");

                    bool alt = false;
                    foreach (var e in r.AuditLogs)
                    {
                        var bg = alt ? "#F8FAFC" : "#FFFFFF";
                        alt = !alt;
                        PdfCell(t, e.Timestamp.ToLocalTime().ToString("yyyy-MM-dd HH:mm"), bg);
                        PdfCell(t, e.ActorName, bg);
                        PdfCell(t, e.Action, bg, bold: true);
                        PdfCell(t, e.Details, bg);
                    }
                });
            });
        }

        // ── PDF helpers ──────────────────────────────────────────────────────────

        private static void PdfTableHeader(TableDescriptor t, string[] headers,
            string bgColor = "#1E40AF")
        {
            foreach (var h in headers)
                t.Cell().Background(bgColor).Padding(6)
                    .Text(h).FontColor("#FFFFFF").Bold().FontSize(8);
        }

        private static void PdfCell(TableDescriptor t, string text, string bg,
            bool bold = false, bool center = false)
        {
            // AlignCenter() must be chained BEFORE Text() — QuestPDF containers are
            // single-child; calling AlignCenter() after Text() assigns a second child.
            var cell = t.Cell().Background(bg).Padding(5);
            var leaf = center ? cell.AlignCenter() : cell;
            var txt  = leaf.Text(text).FontSize(8);
            if (bold) txt.Bold();
        }

        // ── Excel helpers ────────────────────────────────────────────────────────

        private static void WriteHeaderRow(IXLWorksheet ws, int row, string[] headers, string hexColor)
        {
            for (int i = 0; i < headers.Length; i++)
            {
                var cell = ws.Cell(row, i + 1);
                cell.Value = headers[i];
                cell.Style.Font.Bold = true;
                cell.Style.Font.FontColor = XLColor.White;
                cell.Style.Fill.BackgroundColor = XLColor.FromHtml(hexColor);
                cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
            }
        }

        private static void AlternateRow(IXLWorksheet ws, int row, int colCount)
        {
            if (row % 2 == 0)
                ws.Range(row, 1, row, colCount).Style.Fill.BackgroundColor = XLColor.FromHtml("#F8FAFC");
        }

        private static void AutofitColumns(IXLWorksheet ws, int colCount)
        {
            for (int i = 1; i <= colCount; i++)
                ws.Column(i).AdjustToContents();
        }

        // ── Shared ───────────────────────────────────────────────────────────────

        public static string FormatTime(TimeSpan ts)
        {
            if (ts.TotalHours >= 1) return $"{(int)ts.TotalHours}h {ts.Minutes:D2}m";
            if (ts.TotalMinutes >= 1) return $"{ts.Minutes}m";
            return ts.TotalSeconds < 1 ? "—" : $"{ts.Seconds}s";
        }
    }
}
